import type {Metadata} from "next";
// import {Geist, Geist_Mono} from "next/font/google";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Footer from "@/Components/Footer";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add the weights you use
  variable: '--font-poppins', // Optional: CSS variable name
});
// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${poppins.variable}`}
        >
        {/*<Navbar/>*/}
        {children}
        <Footer/>
        </body>
        </html>
    );
}
